# -*- coding: utf-8 -*-
"""matrix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gyTapN2TACcbrHWP8EHkeB_t0209H2H
"""

import numpy as np;
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print("matrix x is:\n",x)
print("matrix y is:\n",y)
a=np.power(x,2)
print("x^2=",a)
result=a+2*y
print("x^2+2*y is \n",result)