# -*- coding: utf-8 -*-
"""pgm10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsuRT5AHbNpRmyugr5FIlgvbPev2chfI
"""

import numpy as np
import pandas as pd
data={'name':['tom','nick','krish','jack'],'age':[20,21,19,18]}
df=pd.DataFrame(data)
print(df)

data={'name':['jai','princi','gaurav','anuj'],'age':[27,24,22,32],'address':['delhi','kanpur','allahabad','kannauj'],'qualification':['msc','ma','mca','phd']}
df=pd.DataFrame(data)
print(df[['name','qualification']])

data=pd.read_csv("/content/details.csv")
data.info()

first=data.head()
print(first)

import pandas as pd
import numpy as np
arr=np.array([10,15,18,22])
s=pd.Series(arr)
print(s)

arr=np.array(['a','b','c','d'])
s=pd.Series(arr,index=['first','second','third','fourth'])
print(s)

s=pd.Series(50,index=[0,1,2,3,4])
print(s)

d={'name':'deepthi','class':'mca','year':2014}
s=pd.Series(d)
print(s)

s=pd.Series([10,15,18,22])
df=pd.DataFrame(s)
df.columns=['List1']
df['List2']=20
df['List3']=df['List1']+df['List2']
print(df)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(0)
values = np.random.randn(100)
s = pd.Series(values) # generate a pandas series
print("series\n",s)
s.plot(kind='hist', title='Normally distributed random values')
plt.show()

s.describe()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(0)
values = np.random.randn(100)
s = pd.Series(values) # generate a pandas series
print("series\n",s)
s.plot(kind='hist', title='Normally distributed random values')
plt.show()

s.describe()

df=pd.DataFrame({'A':[1,2,3,4,5],
                 'B':[12,14,11,16,18],
                 'C':['a','a','b','a','b']})
df

df.describe()

import pandas as pd
df_iris = pd.read_csv('/content/iris.csv')
display(df_iris.head())

import pandas as pd
iris=pd.read_csv('/content/iris.csv')
print(iris.head())

import pandas as pd
df=pd.DataFrame(pd.read_csv("/content/iris.csv"))
df.hist()

iris['sepallength'].hist()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv('/content/iris.csv')
data.info()
data.describe()
data.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv('/content/california.csv')
data.info()
data.describe()
data.head()

import seaborn as sns
import matplotlib.pyplot as plt
data = sns.load_dataset('tips')
sns.scatterplot(x='total_bill', y='tip', data=data)
plt.title('Scatter Plot of Total Bill vs. Tip')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv ('/content/california.csv')
plt.figure(figsize=(10, 8))
sns.scatterplot(x='med_house', y='ho_me_age',
data=data)
plt.title('Scatter Plot for Median House Value vs. Housing Median Age')
plt.xlabel('Median House Value')
plt.ylabel('Housing Median Age')
plt.show()

plt.figure(figsize=(15, 10))
sns.boxplot(x='ho_me_age', y='med_house', data=data)
plt.title('Box Plot for Housing Median Age by Median House Value')
plt.show()