# -*- coding: utf-8 -*-
"""program1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSEl13w56WBqpXU_1u5L6Tr7MtFHfCi7
"""

import numpy as n
matrix1 = np.array([[1, 2, 3], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [3, 2, 1]])
matrix_sum = matrix1 + matrix2
matrix_diff = np.divide(matrix1, matrix2)
matrix_product = matrix1 * matrix2
matrix_multiply = np.dot(matrix1, matrix2.T)
matrix1_transpose = matrix1.T
diagonal_sum = np.trace(matrix1[:, :2])
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Matrix Sum:\n", matrix_sum)
print("Matrix Difference (Element-wise Division):\n", matrix_diff)
print("Matrix Element-wise Product:\n", matrix_product)
print("Matrix Multiplication (Dot Product):\n", matrix_multiply)
print("Transpose of Matrix1:\n", matrix1_transpose)
print("Sum of Diagonal Elements of Matrix1 (first 2x2):", diagonal_sum)

import numpy as np;
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print("matrix x is:\n",x)
print("matrix y is:\n",y)
a=np.power(x,2)
print("x**2",a)
result=a+2*y
print("x**2+2*y is \n",result)

import numpy as np
A=np.array([[2,-1,2],[3,0,1],[1,1,-1]])
b=np.array([-3,5,-2])
x=np.linalg.solve(A,b)
print("matrix A:")
print(A)
print("vector b:")
print(b)
print("solution for x:")
print(x)