# -*- coding: utf-8 -*-
"""program 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-_tH8KxBP3AtagzajPwz5edMb85JnGi
"""

import matplotlib.pyplot as plt
years=[2001,2002,2003,2004,2005,2006,2007]
car_values=[24000,22500,19700,17500,14500,10000,5800]
plt.figure(figsize=(10,6))
plt.subplot(111)
plt.plot(years,car_values,linestyle='-',color='red',marker='*',markersize=20,markerfacecolor='green')
plt.title("\nMCA 2023-2025",loc="right")
plt.title("value Depreciation",loc="left")
plt.xlabel("year")
plt.ylabel("car value")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
month = np.array(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
AS = np.array([173,153,195,147,120,144,148,109,174,130,172,131])
LS = np.array([189,189,105,112,173,109,151,197,174,145,177,161])
SLS = np.array([185,185,126,134,196,153,112,133,200,145,167,110])
plt.xlabel('Months of Year', fontsize=18)
plt.ylabel('Sales of Segments')
plt.title('Sales Data')
plt.title('MCA 2023-2025', loc='right')
plt.scatter(month,AS, label='Affordable Segment', color='pink')
plt.scatter(month,LS, label='Luxury Segment', color='yellow')
plt.scatter(month,SLS, label='Super Luxury Segment', color='blue')
plt.show()