# -*- coding: utf-8 -*-
"""subplots

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhaNiXvDflvy4x5b4ACSwRew3Q3iU__i
"""

import matplotlib.pyplot as plt
  import numpy as np
  x=np.linspace(0,10,100)
  y1=np.sin(x)
  y2=np.cos(x)
  fig,axs=plt.subplots(2,1, figsize=(8,8))

  axs[0].plot(x,y1,'b')
  axs[0].set_title('sine function')
  axs[0].set_ylabel('sin(x)')
  axs[1].plot(x,y2,'r')
  axs[1].set_title('cosine function')
  axs[1].set_ylabel('cosx(x)')
  axs[1].set_xlabel('x')
  plt.tight_layout()
  plt.show()